---
driver:
  name: vagrant
  provider: vmware_fusion

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: macosx-10.11
    box_url: ''
  - name: macosx-10.12
    box_url: ''

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[xcode-tests::default]
    verifier:
      inspec_tests:
        - test/recipes
